name: Second Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: information sur la machine
        run: hostnamectl
      - name: adressage ipv4
        run: ip -4 a
      - name: mon identit√© de connexion
        run: who am i
