name: Workflow-9-release-tag

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  c-release:
    runs-on: ubuntu-latest
    steps:
      - name: make release
        uses: softprops/action-gh-release@v2
        with:
          body: "New release C : ${{ github.ref_name }}"
          draft: false
