name: Fourth Workflow
on: push
jobs:
  compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: make folder
        run: mkdir bin
      - name: compilation
        run: make build
